name: Generate PDF, TeX, and HTML

on:
  push:
    paths:
      - 'main.tex'

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache MacTeX installation to speed up future runs
      - name: Cache MacTeX
        uses: actions/cache@v3
        with:
          path: /Library/TeX
          key: macos-mactex-${{ runner.os }}-${{ hashFiles('main.tex') }}
          restore-keys: |
            macos-mactex-${{ runner.os }}-

      # Install MacTeX if not cached
      - name: Install MacTeX
        run: |
          if [ ! -d "/Library/TeX/texbin" ]; then
            brew install --cask mactex
          fi

      # Add MacTeX to PATH
      - name: Add MacTeX to PATH
        run: echo "/Library/TeX/texbin" >> $GITHUB_PATH

      # Calculate version number based on changes
      - name: Calculate version number
        id: version
        run: |
          if [ ! -f .version ]; then 
            echo "1.1" > .version
          fi
          VERSION=$(cat .version)
          CHANGES=$(git diff HEAD~1 --numstat main.tex | awk '{print $1 + $2}')
          if [ "$CHANGES" -gt 0 ]; then
            # Increment version (you can adjust this logic)
            VERSION_MAJOR=$(echo $VERSION | cut -d'.' -f1)
            VERSION_MINOR=$(echo $VERSION | cut -d'.' -f2)
            VERSION_MINOR=$((VERSION_MINOR + 0.1))
            VERSION="${VERSION_MAJOR}.${VERSION_MINOR}"
          fi
          echo $VERSION > .version
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" # Output version for debugging

      # Generate PDF
      - name: Generate PDF
        run: pdflatex -interaction=nonstopmode main.tex

      # Generate HTML
      - name: Generate HTML
        run: htlatex main.tex

      # Rename files with version number
      - name: Rename files
        run: |
          VERSION=$(cat .version)
          mv main.pdf "output-${VERSION}.pdf"
          mv main.tex "output-${VERSION}.tex"
          mv main.html "output-${VERSION}.html"

      # Upload generated files as artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-files
          path: |
            output-$(cat .version).pdf
            output-$(cat .version).tex
            output-$(cat .version).html
